blank_issues_enabled: false
contact_links:
  - name: Aloazny
    url: https://github.com/Aloazny/AppOpt_Aloazny/issues
    about: 请在此反馈问题.
  - name: 教程参考
    url: https://www.coolapk.com/feed/65261377?s=ZmY0ZGI4NTU1NTJlN2VnNjg3Y2U5MjR6a1511
    about: 查看线程亲和获取模块使用教程
  - name: 模块下载
    url: https://aloazny.lanzouo.com/b00jea2q6j
    about: 下载线程亲和获取模块（密码：111）